<!DOCTYPE html>
<html lang="ru" translate="no">
<head>
<meta name="google" content="notranslate"><meta charset="utf-8"><meta name="viewport" content="width=device-width,initial-scale=1,viewport-fit=cover"><meta name="theme-color" content="#081a31">
<title>Управление группой — SkyGuardian</title>
<style>
:root{--nav:#081a31;--nav2:#0a2742;--blue:#246fdb;--text:#1d2a3c;--muted:#7c8798;--line:#e8edf3;--bg:#f7f9fc}*{box-sizing:border-box}html,body{margin:0;min-height:100%;font-family:Inter,system-ui,-apple-system,"Segoe UI",sans-serif;color:var(--text);background:var(--bg)}a{text-decoration:none;color:inherit}.app{min-height:100vh;display:grid;grid-template-columns:302px minmax(0,1fr)}.sidebar{position:sticky;top:0;height:100vh;padding:28px 20px;background:linear-gradient(180deg,var(--nav),var(--nav2));color:#edf4ff}.brand{display:flex;align-items:center;gap:12px;margin:0 4px 28px;font-size:21px;font-weight:800}.brand-mark{width:38px;height:44px;display:grid;place-items:center;background:linear-gradient(145deg,#31a5ff,#1359df);clip-path:polygon(50% 0,95% 18%,90% 67%,50% 100%,10% 67%,5% 18%)}.nav-home,.nav-title,.nav-sub{display:flex;align-items:center;gap:13px}.nav-home{padding:17px 16px}.nav-group{padding:25px 8px 20px;border-bottom:1px solid rgba(255,255,255,.09)}.nav-title{font-size:15px;font-weight:800;text-transform:uppercase}.nav-sub{margin-top:6px;padding:12px 10px 12px 21px;color:#d5dfeb;border-radius:9px}.nav-sub.active{background:linear-gradient(90deg,#2266cb,#2c74dd);color:#fff}.dot{width:8px;height:8px;border-radius:50%;background:#879ab5}.logout{width:100%;margin-top:24px;padding:13px 16px;border:1px solid rgba(255,255,255,.13);border-radius:10px;background:rgba(255,255,255,.05);color:#e8f0fa;text-align:left}.main{padding:34px 30px}.topbar{display:flex;align-items:center;gap:14px}.menu-btn{display:none;width:44px;height:44px;border:0;border-radius:11px;background:#fff}.heading h1{margin:0;font-size:36px}.heading p{margin:8px 0 0;color:var(--muted)}.content{max-width:920px;margin-top:28px}.card{padding:24px;background:#fff;border:1px solid var(--line);border-radius:18px}.card h2{margin:0;font-size:21px}.card p{margin:10px 0 0;color:var(--muted);line-height:1.55}.empty{margin-top:20px;padding:22px;border:1px dashed #cbd6e4;border-radius:14px;background:#f8fafc}.overlay{display:none}@media(max-width:800px){.app{display:block}.sidebar{position:fixed;left:0;top:0;width:292px;transform:translateX(-105%);transition:.22s;z-index:30}body.menu-open .sidebar{transform:translateX(0)}.overlay{display:block;position:fixed;inset:0;background:rgba(2,10,23,.52);opacity:0;pointer-events:none;z-index:20}body.menu-open .overlay{opacity:1;pointer-events:auto}.main{padding:20px 16px}.menu-btn{display:grid;place-items:center}.heading h1{font-size:29px}}
</style>
</head><body>
<div class="overlay" onclick="document.body.classList.remove('menu-open')"></div><div class="app"><aside class="sidebar">
<div class="brand"><span class="brand-mark">✈</span><span>SkyGuardian</span></div><a class="nav-home" href="{{ route('dashboard') }}">⌂ <span>Главная</span></a>
<div class="nav-group"><div class="nav-title">▦ <span>Новости</span></div><a class="nav-sub" href="{{ route('news.sources') }}"><span class="dot"></span>Источники бота</a><a class="nav-sub" href="{{ route('news.settings') }}"><span class="dot"></span>Настройки бота</a></div>
<div class="nav-group"><div class="nav-title">♟ <span>Воздушная тревога</span></div><a class="nav-sub" href="{{ route('alerts.sources') }}"><span class="dot"></span>Источники бота</a><a class="nav-sub" href="{{ route('alerts.settings') }}"><span class="dot"></span>Настройки бота</a></div>
<div class="nav-group"><div class="nav-title">✹ <span>Общие настройки</span></div><a class="nav-sub active" href="{{ route('users.index') }}"><span class="dot"></span>Управление группой</a></div>
<form method="POST" action="{{ route('logout') }}">@csrf<button class="logout">Выйти</button></form></aside>
<main class="main"><div class="topbar"><button class="menu-btn" type="button" onclick="document.body.classList.add('menu-open')">☰</button><div class="heading"><h1>Управление группой</h1><p>Общие параметры Telegram-группы SkyGuardian</p></div></div><div class="content"><section class="card"><h2>Настройки группы</h2><p>Здесь будет централизованное управление общей группой: название, Telegram ID, права публикации, администраторы и служебные параметры.</p><div class="empty">Страница создана. Функциональные поля добавим отдельными пунктами после утверждения структуры управления группой.</div></section></div></main></div>
</body></html>
