name: Server Command

on:
  workflow_dispatch:
    inputs:
      command:
        description: "Команда для сервера"
        required: true
        type: string

jobs:
  execute:
    runs-on: self-hosted

    steps:
      - name: Run command
        shell: bash
        env:
          SERVER_COMMAND: ${{ inputs.command }}
        run: |
          bash -lc "$SERVER_COMMAND"
